//! Ground truth tests. Discriminators, base58 constants, and PDA vectors in
//! this file were generated by an independent pure Python implementation
//! (hashlib sha256 plus a from scratch ed25519 decompression check), so the
//! Rust code is verified against something it did not produce. Round trip
//! tests then pin the wire formats.

use quorum_core::message::{
    compile_legacy_message, parse_tx_base64, shortvec_len, shortvec_read, unsigned_tx_base64,
    AccountMeta, Instruction,
};
use quorum_core::policy::Policy;
use quorum_core::pubkey::{find_program_address, Pubkey};
use quorum_core::spl::{
    derive_ata, format_base_amount, parse_ui_amount, ATA_PROGRAM, MEMO_PROGRAM, TOKEN22_PROGRAM,
    TOKEN_PROGRAM,
};
use quorum_core::squads::{
    compile_transaction_message, decode_multisig, decode_proposal, encode_multisig_for_test,
    encode_proposal_for_test, multisig_pda, proposal_create_ix, proposal_pda, transaction_pda,
    vault_pda, vault_transaction_create_ix, Member, MultisigState, ProposalState, ProposalStatus,
    DISC_PROPOSAL_CREATE, DISC_VAULT_TRANSACTION_CREATE, SQUADS_PROGRAM,
};
use serde_json::json;

#[test]
fn base58_constants_match_known_ids() {
    assert_eq!(
        SQUADS_PROGRAM.to_base58(),
        "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf"
    );
    assert_eq!(
        TOKEN_PROGRAM.to_base58(),
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
    );
    assert_eq!(
        TOKEN22_PROGRAM.to_base58(),
        "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
    );
    assert_eq!(
        ATA_PROGRAM.to_base58(),
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
    );
    assert_eq!(
        MEMO_PROGRAM.to_base58(),
        "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
    );
}

#[test]
fn discriminators_match_python_sha256() {
    assert_eq!(DISC_VAULT_TRANSACTION_CREATE, [48, 250, 78, 168, 208, 226, 218, 211]);
    assert_eq!(DISC_PROPOSAL_CREATE, [220, 60, 73, 224, 30, 108, 79, 159]);
}

fn usdc() -> Pubkey {
    Pubkey::from_base58("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v").unwrap()
}

#[test]
fn pda_vectors_match_python_ed25519() {
    // Synthetic fixed keys used by the Python generator.
    let owner = Pubkey([7u8; 32]);
    let create_key = Pubkey([9u8; 32]);

    let ata = derive_ata(&owner, &usdc(), &TOKEN_PROGRAM);
    assert_eq!(ata.to_base58(), "7EJSueeCjseYzghxU2XhcGEUn7RJDh43Z2dL6dvGy9mw");

    let (ms, ms_bump) = multisig_pda(&create_key);
    assert_eq!(ms.to_base58(), "F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68");
    assert_eq!(ms_bump, 253);

    let (vault, vault_bump) = vault_pda(&ms, 0);
    assert_eq!(vault.to_base58(), "DpcyqkendyzQd6yvDyHt9BEpUp2EnmXbEFUnpqAXpFAZ");
    assert_eq!(vault_bump, 254);

    let (tx, _) = transaction_pda(&ms, 1);
    assert_eq!(tx.to_base58(), "9FH2Z2R5jZNjFe2LbaWq5uo4DWAJHYehsZDe4MKYRwos");

    let (prop, prop_bump) = proposal_pda(&ms, 1);
    assert_eq!(prop.to_base58(), "FbLJoWRqPC4xyAU8nrHXdojvpg6G6c8pHNuW35Mzdt13");
    assert_eq!(prop_bump, 253);
}

#[test]
fn pda_is_off_curve_and_reproducible() {
    let program = SQUADS_PROGRAM;
    let (pk, bump) = find_program_address(&[b"multisig", b"quorum-test"], &program);
    assert!(!pk.is_on_curve());
    let (pk2, bump2) = find_program_address(&[b"multisig", b"quorum-test"], &program);
    assert_eq!(pk, pk2);
    assert_eq!(bump, bump2);
}

#[test]
fn shortvec_roundtrip() {
    for n in [0usize, 1, 5, 127, 128, 300, 16383, 16384] {
        let mut buf = Vec::new();
        shortvec_len(n, &mut buf);
        let (m, used) = shortvec_read(&buf).unwrap();
        assert_eq!(n, m);
        assert_eq!(used, buf.len());
    }
}

#[test]
fn transaction_message_wire_bytes_are_exact() {
    // A one instruction inner message with a known layout, checked byte by
    // byte against the SmallVec encoding rules in the Squads source: u8
    // length prefixes everywhere except instruction data, which is u16 LE.
    let vault = Pubkey([1u8; 32]);
    let dest = Pubkey([2u8; 32]);
    let ix = Instruction {
        program_id: Pubkey([3u8; 32]),
        accounts: vec![
            AccountMeta::writable(vault, true),
            AccountMeta::writable(dest, false),
        ],
        data: vec![0xAA, 0xBB, 0xCC],
    };
    let wire = compile_transaction_message(&vault, &[ix]).unwrap();

    let mut expected = Vec::new();
    expected.push(1); // num_signers
    expected.push(1); // num_writable_signers
    expected.push(1); // num_writable_non_signers
    expected.push(3); // account_keys len (u8)
    expected.extend_from_slice(&[1u8; 32]); // vault: writable signer
    expected.extend_from_slice(&[2u8; 32]); // dest: writable non signer
    expected.extend_from_slice(&[3u8; 32]); // program: readonly non signer
    expected.push(1); // instructions len (u8)
    expected.push(2); // program_id_index
    expected.push(2); // account_indexes len (u8)
    expected.push(0); // vault index
    expected.push(1); // dest index
    expected.extend_from_slice(&3u16.to_le_bytes()); // data len (u16 LE)
    expected.extend_from_slice(&[0xAA, 0xBB, 0xCC]);
    expected.push(0); // address_table_lookups len (u8)
    assert_eq!(wire, expected);
}

#[test]
fn vault_transaction_create_arg_bytes_are_exact() {
    let ms = Pubkey([4u8; 32]);
    let tx = Pubkey([5u8; 32]);
    let creator = Pubkey([6u8; 32]);
    let msg = vec![9u8, 9, 9];
    let ix = vault_transaction_create_ix(&ms, &tx, &creator, &creator, 0, 0, &msg, Some("inv-1".into()));
    let mut expected = Vec::new();
    expected.extend_from_slice(&DISC_VAULT_TRANSACTION_CREATE);
    expected.push(0); // vault_index
    expected.push(0); // ephemeral_signers
    expected.extend_from_slice(&3u32.to_le_bytes()); // Vec<u8> borsh length
    expected.extend_from_slice(&[9, 9, 9]);
    expected.push(1); // Some
    expected.extend_from_slice(&5u32.to_le_bytes());
    expected.extend_from_slice(b"inv-1");
    assert_eq!(ix.data, expected);
    assert_eq!(ix.accounts.len(), 5);
    assert!(ix.accounts[0].is_writable && !ix.accounts[0].is_signer); // multisig
    assert!(ix.accounts[2].is_signer && !ix.accounts[2].is_writable); // creator
    assert!(ix.accounts[3].is_signer && ix.accounts[3].is_writable); // rent payer
}

#[test]
fn proposal_create_arg_bytes_are_exact() {
    let ms = Pubkey([4u8; 32]);
    let prop = Pubkey([5u8; 32]);
    let creator = Pubkey([6u8; 32]);
    let ix = proposal_create_ix(&ms, &prop, &creator, &creator, 7, false);
    let mut expected = Vec::new();
    expected.extend_from_slice(&DISC_PROPOSAL_CREATE);
    expected.extend_from_slice(&7u64.to_le_bytes());
    expected.push(0);
    assert_eq!(ix.data, expected);
}

#[test]
fn multisig_account_roundtrip() {
    let state = MultisigState {
        create_key: Pubkey([9u8; 32]),
        config_authority: Pubkey::ZERO,
        threshold: 2,
        time_lock: 0,
        transaction_index: 41,
        stale_transaction_index: 3,
        rent_collector: None,
        bump: 253,
        members: vec![
            Member { key: Pubkey([1u8; 32]), permissions: 7 },
            Member { key: Pubkey([2u8; 32]), permissions: 1 },
        ],
    };
    let bytes = encode_multisig_for_test(&state);
    let decoded = decode_multisig(&bytes).unwrap();
    assert_eq!(decoded.threshold, 2);
    assert_eq!(decoded.transaction_index, 41);
    assert_eq!(decoded.members.len(), 2);
    assert_eq!(decoded.members[1].permissions, 1); // initiate only
}

#[test]
fn proposal_account_roundtrip() {
    let state = ProposalState {
        multisig: Pubkey([4u8; 32]),
        transaction_index: 42,
        status: ProposalStatus::Active(1_700_000_000),
        bump: 250,
        approved: vec![Pubkey([1u8; 32])],
        rejected: vec![],
        cancelled: vec![],
    };
    let bytes = encode_proposal_for_test(&state);
    let decoded = decode_proposal(&bytes).unwrap();
    assert_eq!(decoded.transaction_index, 42);
    assert_eq!(decoded.status.label(), "Active");
    assert_eq!(decoded.approved.len(), 1);
}

#[test]
fn legacy_message_roundtrips_through_parser() {
    let payer = Pubkey([1u8; 32]);
    let dest = Pubkey([2u8; 32]);
    let ix = quorum_core::spl::system_transfer_ix(&payer, &dest, 42);
    let msg = compile_legacy_message(&payer, &[ix], &[7u8; 32]).unwrap();
    let b64 = unsigned_tx_base64(&msg);
    let parsed = parse_tx_base64(&b64).unwrap();
    assert_eq!(parsed.num_required_signatures, 1);
    assert_eq!(parsed.instructions.len(), 1);
    assert_eq!(parsed.instructions[0].program_id, Pubkey::ZERO);
    assert_eq!(parsed.instructions[0].data[4..12], 42u64.to_le_bytes());
    assert_eq!(parsed.recent_blockhash, [7u8; 32]);
}

#[test]
fn amount_parsing_is_exact_and_fails_closed() {
    assert_eq!(parse_ui_amount("25", 6).unwrap(), 25_000_000);
    assert_eq!(parse_ui_amount("12.5", 6).unwrap(), 12_500_000);
    assert_eq!(parse_ui_amount("0.000001", 6).unwrap(), 1);
    assert!(parse_ui_amount("0.0000001", 6).is_err()); // too many places
    assert!(parse_ui_amount("-5", 6).is_err());
    assert!(parse_ui_amount("1e6", 6).is_err());
    assert!(parse_ui_amount("", 6).is_err());
    assert!(parse_ui_amount("0", 6).is_err());
    assert_eq!(format_base_amount(12_500_000, 6), "12.5");
    assert_eq!(format_base_amount(25_000_000, 6), "25");
}

#[test]
fn policy_fails_closed_and_rejects_raw_addresses() {
    // No config at all: refuse.
    assert!(Policy::from_config(&json!({})).is_err());
    // Empty allowlist: refuse.
    assert!(Policy::from_config(&json!({"mints": [], "recipients": {"a": "x"}})).is_err());

    let cfg = json!({
        "mints": [{
            "mint": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
            "symbol": "USDC",
            "decimals": 6,
            "per_proposal_cap": "500"
        }],
        "recipients": {
            "ana": "F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68"
        }
    });
    let p = Policy::from_config(&cfg).unwrap();
    assert!(p.resolve_mint("usdc").is_ok());
    assert!(p.resolve_mint("BONK").is_err());
    assert!(p.resolve_recipient("Ana").is_ok());
    // A valid raw base58 address is still refused by design.
    assert!(p
        .resolve_recipient("DpcyqkendyzQd6yvDyHt9BEpUp2EnmXbEFUnpqAXpFAZ")
        .is_err());
    let rule = p.resolve_mint("USDC").unwrap();
    assert!(p.check_amount(rule, "500").is_ok());
    assert!(p.check_amount(rule, "500.000001").is_err());
}

#[test]
fn policy_parses_the_host_flat_string_config() {
    // The ZeroClaw host stores plugin config as HashMap<String, String>
    // (crates/zeroclaw-config PluginEntryConfig) and injects `__config` as a
    // flat JSON object of strings, so structured values arrive as JSON in a
    // string. This is the exact shape call_execute produces.
    let cfg = json!({
        "rpc_url": "https://api.mainnet-beta.solana.com",
        "mints": "[{\"mint\":\"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\
                    \"symbol\":\"USDC\",\"decimals\":6,\"per_proposal_cap\":\"500\"}]",
        "recipients": "{\"ana\":\"F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68\"}",
        "max_memo_len": "64"
    });
    let p = Policy::from_config(&cfg).unwrap();
    assert!(p.resolve_mint("usdc").is_ok());
    assert!(p.resolve_recipient("ana").is_ok());
    assert_eq!(p.max_memo_len, 64);

    // Malformed JSON inside the string is a loud refusal, not a missing key.
    let bad = json!({
        "mints": "[{\"mint\": nope]",
        "recipients": "{\"ana\":\"F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68\"}"
    });
    let err = Policy::from_config(&bad).unwrap_err();
    assert!(err.contains("not valid JSON"), "got: {err}");

    // A present but non-numeric max_memo_len refuses instead of silently
    // defaulting.
    let bad_len = json!({
        "mints": "[{\"mint\":\"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\
                    \"symbol\":\"USDC\",\"decimals\":6,\"per_proposal_cap\":\"500\"}]",
        "recipients": "{\"ana\":\"F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68\"}",
        "max_memo_len": "lots"
    });
    assert!(Policy::from_config(&bad_len).is_err());
}
