//! Ground truth tests. Discriminators, base58 constants, and PDA vectors in
//! this file were generated by an independent pure Python implementation
//! (hashlib sha256 plus a from scratch ed25519 decompression check), so the
//! Rust code is verified against something it did not produce. Round trip
//! tests then pin the wire formats.

use quorum_core::message::{
    compile_legacy_message, parse_tx_base64, shortvec_len, shortvec_read, unsigned_tx_base64,
    AccountMeta, Instruction,
};
use quorum_core::policy::Policy;
use quorum_core::pubkey::{find_program_address, Pubkey};
use quorum_core::spl::{
    derive_ata, format_base_amount, parse_ui_amount, ATA_PROGRAM, MEMO_PROGRAM, TOKEN22_PROGRAM,
    TOKEN_PROGRAM,
};
use quorum_core::squads::{
    compile_transaction_message, decode_multisig, decode_proposal,
    decode_vault_transaction_create_args, encode_multisig_for_test, encode_proposal_for_test,
    multisig_pda, proposal_create_ix, proposal_pda, transaction_pda, vault_pda,
    vault_transaction_create_ix, Member, MultisigState, ProposalState, ProposalStatus,
    ACCT_MULTISIG, ACCT_PROPOSAL, DISC_PROPOSAL_APPROVE, DISC_PROPOSAL_CREATE,
    DISC_VAULT_TRANSACTION_CREATE, SQUADS_PROGRAM,
};
use serde_json::{json, Value};

#[test]
fn base58_constants_match_known_ids() {
    assert_eq!(
        SQUADS_PROGRAM.to_base58(),
        "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf"
    );
    assert_eq!(
        TOKEN_PROGRAM.to_base58(),
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
    );
    assert_eq!(
        TOKEN22_PROGRAM.to_base58(),
        "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
    );
    assert_eq!(
        ATA_PROGRAM.to_base58(),
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
    );
    assert_eq!(
        MEMO_PROGRAM.to_base58(),
        "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
    );
}

/// Anchor discriminators are the first 8 bytes of sha256 of a namespaced
/// name: "global:<instruction>" for instructions, "account:<Account>" for
/// account structs. Re-derive them here so the shipped constants are checked
/// against a real hash of the Squads v4 names, not against their own literals.
fn anchor_disc(namespace: &str, name: &str) -> [u8; 8] {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(format!("{namespace}:{name}").as_bytes());
    let d = h.finalize();
    let mut out = [0u8; 8];
    out.copy_from_slice(&d[..8]);
    out
}

#[test]
fn discriminators_derive_from_sha256_of_squads_names() {
    assert_eq!(
        DISC_VAULT_TRANSACTION_CREATE,
        anchor_disc("global", "vault_transaction_create")
    );
    assert_eq!(
        DISC_PROPOSAL_CREATE,
        anchor_disc("global", "proposal_create")
    );
    assert_eq!(
        DISC_PROPOSAL_APPROVE,
        anchor_disc("global", "proposal_approve")
    );
    assert_eq!(ACCT_MULTISIG, anchor_disc("account", "Multisig"));
    assert_eq!(ACCT_PROPOSAL, anchor_disc("account", "Proposal"));
}

fn usdc() -> Pubkey {
    Pubkey::from_base58("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v").unwrap()
}

#[test]
fn pda_vectors_match_python_ed25519() {
    // Synthetic fixed keys used by the Python generator.
    let owner = Pubkey([7u8; 32]);
    let create_key = Pubkey([9u8; 32]);

    let ata = derive_ata(&owner, &usdc(), &TOKEN_PROGRAM);
    assert_eq!(
        ata.to_base58(),
        "7EJSueeCjseYzghxU2XhcGEUn7RJDh43Z2dL6dvGy9mw"
    );

    let (ms, ms_bump) = multisig_pda(&create_key);
    assert_eq!(
        ms.to_base58(),
        "F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68"
    );
    assert_eq!(ms_bump, 253);

    let (vault, vault_bump) = vault_pda(&ms, 0);
    assert_eq!(
        vault.to_base58(),
        "DpcyqkendyzQd6yvDyHt9BEpUp2EnmXbEFUnpqAXpFAZ"
    );
    assert_eq!(vault_bump, 254);

    let (tx, _) = transaction_pda(&ms, 1);
    assert_eq!(
        tx.to_base58(),
        "9FH2Z2R5jZNjFe2LbaWq5uo4DWAJHYehsZDe4MKYRwos"
    );

    let (prop, prop_bump) = proposal_pda(&ms, 1);
    assert_eq!(
        prop.to_base58(),
        "FbLJoWRqPC4xyAU8nrHXdojvpg6G6c8pHNuW35Mzdt13"
    );
    assert_eq!(prop_bump, 253);
}

#[test]
fn pda_is_off_curve_and_reproducible() {
    let program = SQUADS_PROGRAM;
    let (pk, bump) = find_program_address(&[b"multisig", b"quorum-test"], &program);
    assert!(!pk.is_on_curve());
    let (pk2, bump2) = find_program_address(&[b"multisig", b"quorum-test"], &program);
    assert_eq!(pk, pk2);
    assert_eq!(bump, bump2);
}

#[test]
fn shortvec_roundtrip() {
    for n in [0usize, 1, 5, 127, 128, 300, 16383, 16384] {
        let mut buf = Vec::new();
        shortvec_len(n, &mut buf);
        let (m, used) = shortvec_read(&buf).unwrap();
        assert_eq!(n, m);
        assert_eq!(used, buf.len());
    }
}

#[test]
fn transaction_message_wire_bytes_are_exact() {
    // A one instruction inner message with a known layout, checked byte by
    // byte against the SmallVec encoding rules in the Squads source: u8
    // length prefixes everywhere except instruction data, which is u16 LE.
    let vault = Pubkey([1u8; 32]);
    let dest = Pubkey([2u8; 32]);
    let ix = Instruction {
        program_id: Pubkey([3u8; 32]),
        accounts: vec![
            AccountMeta::writable(vault, true),
            AccountMeta::writable(dest, false),
        ],
        data: vec![0xAA, 0xBB, 0xCC],
    };
    let wire = compile_transaction_message(&vault, &[ix]).unwrap();

    let mut expected = Vec::new();
    expected.push(1); // num_signers
    expected.push(1); // num_writable_signers
    expected.push(1); // num_writable_non_signers
    expected.push(3); // account_keys len (u8)
    expected.extend_from_slice(&[1u8; 32]); // vault: writable signer
    expected.extend_from_slice(&[2u8; 32]); // dest: writable non signer
    expected.extend_from_slice(&[3u8; 32]); // program: readonly non signer
    expected.push(1); // instructions len (u8)
    expected.push(2); // program_id_index
    expected.push(2); // account_indexes len (u8)
    expected.push(0); // vault index
    expected.push(1); // dest index
    expected.extend_from_slice(&3u16.to_le_bytes()); // data len (u16 LE)
    expected.extend_from_slice(&[0xAA, 0xBB, 0xCC]);
    expected.push(0); // address_table_lookups len (u8)
    assert_eq!(wire, expected);
}

#[test]
fn vault_transaction_create_arg_bytes_are_exact() {
    let ms = Pubkey([4u8; 32]);
    let tx = Pubkey([5u8; 32]);
    let creator = Pubkey([6u8; 32]);
    let msg = vec![9u8, 9, 9];
    let ix = vault_transaction_create_ix(
        &ms,
        &tx,
        &creator,
        &creator,
        0,
        0,
        &msg,
        Some("inv-1".into()),
    );
    let mut expected = Vec::new();
    expected.extend_from_slice(&DISC_VAULT_TRANSACTION_CREATE);
    expected.push(0); // vault_index
    expected.push(0); // ephemeral_signers
    expected.extend_from_slice(&3u32.to_le_bytes()); // Vec<u8> borsh length
    expected.extend_from_slice(&[9, 9, 9]);
    expected.push(1); // Some
    expected.extend_from_slice(&5u32.to_le_bytes());
    expected.extend_from_slice(b"inv-1");
    assert_eq!(ix.data, expected);
    assert_eq!(ix.accounts.len(), 5);
    assert!(ix.accounts[0].is_writable && !ix.accounts[0].is_signer); // multisig
    assert!(ix.accounts[2].is_signer && !ix.accounts[2].is_writable); // creator
    assert!(ix.accounts[3].is_signer && ix.accounts[3].is_writable); // rent payer
}

#[test]
fn proposal_create_arg_bytes_are_exact() {
    let ms = Pubkey([4u8; 32]);
    let prop = Pubkey([5u8; 32]);
    let creator = Pubkey([6u8; 32]);
    let ix = proposal_create_ix(&ms, &prop, &creator, &creator, 7, false);
    let mut expected = Vec::new();
    expected.extend_from_slice(&DISC_PROPOSAL_CREATE);
    expected.extend_from_slice(&7u64.to_le_bytes());
    expected.push(0);
    assert_eq!(ix.data, expected);
}

#[test]
fn multisig_account_roundtrip() {
    let state = MultisigState {
        create_key: Pubkey([9u8; 32]),
        config_authority: Pubkey::ZERO,
        threshold: 2,
        time_lock: 0,
        transaction_index: 41,
        stale_transaction_index: 3,
        rent_collector: None,
        bump: 253,
        members: vec![
            Member {
                key: Pubkey([1u8; 32]),
                permissions: 7,
            },
            Member {
                key: Pubkey([2u8; 32]),
                permissions: 1,
            },
        ],
    };
    let bytes = encode_multisig_for_test(&state);
    let decoded = decode_multisig(&bytes).unwrap();
    assert_eq!(decoded.threshold, 2);
    assert_eq!(decoded.transaction_index, 41);
    assert_eq!(decoded.members.len(), 2);
    assert_eq!(decoded.members[1].permissions, 1); // initiate only
}

#[test]
fn proposal_account_roundtrip() {
    let state = ProposalState {
        multisig: Pubkey([4u8; 32]),
        transaction_index: 42,
        status: ProposalStatus::Active(1_700_000_000),
        bump: 250,
        approved: vec![Pubkey([1u8; 32])],
        rejected: vec![],
        cancelled: vec![],
    };
    let bytes = encode_proposal_for_test(&state);
    let decoded = decode_proposal(&bytes).unwrap();
    assert_eq!(decoded.transaction_index, 42);
    assert_eq!(decoded.status.label(), "Active");
    assert_eq!(decoded.approved.len(), 1);
}

#[test]
fn legacy_message_roundtrips_through_parser() {
    let payer = Pubkey([1u8; 32]);
    let dest = Pubkey([2u8; 32]);
    let ix = quorum_core::spl::system_transfer_ix(&payer, &dest, 42);
    let msg = compile_legacy_message(&payer, &[ix], &[7u8; 32]).unwrap();
    let b64 = unsigned_tx_base64(&msg);
    let parsed = parse_tx_base64(&b64).unwrap();
    assert_eq!(parsed.num_required_signatures, 1);
    assert_eq!(parsed.instructions.len(), 1);
    assert_eq!(parsed.instructions[0].program_id, Pubkey::ZERO);
    assert_eq!(parsed.instructions[0].data[4..12], 42u64.to_le_bytes());
    assert_eq!(parsed.recent_blockhash, [7u8; 32]);
}

#[test]
fn amount_parsing_is_exact_and_fails_closed() {
    assert_eq!(parse_ui_amount("25", 6).unwrap(), 25_000_000);
    assert_eq!(parse_ui_amount("12.5", 6).unwrap(), 12_500_000);
    assert_eq!(parse_ui_amount("0.000001", 6).unwrap(), 1);
    assert!(parse_ui_amount("0.0000001", 6).is_err()); // too many places
    assert!(parse_ui_amount("-5", 6).is_err());
    assert!(parse_ui_amount("1e6", 6).is_err());
    assert!(parse_ui_amount("", 6).is_err());
    assert!(parse_ui_amount("0", 6).is_err());
    assert_eq!(format_base_amount(12_500_000, 6), "12.5");
    assert_eq!(format_base_amount(25_000_000, 6), "25");
}

#[test]
fn policy_fails_closed_and_rejects_raw_addresses() {
    // No config at all: refuse.
    assert!(Policy::from_config(&json!({})).is_err());
    // Empty allowlist: refuse.
    assert!(Policy::from_config(&json!({"mints": [], "recipients": {"a": "x"}})).is_err());

    let cfg = json!({
        "mints": [{
            "mint": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
            "symbol": "USDC",
            "decimals": 6,
            "per_proposal_cap": "500"
        }],
        "recipients": {
            "ana": "F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68"
        }
    });
    let p = Policy::from_config(&cfg).unwrap();
    assert!(p.resolve_mint("usdc").is_ok());
    assert!(p.resolve_mint("BONK").is_err());
    assert!(p.resolve_recipient("Ana").is_ok());
    // A valid raw base58 address is still refused by design.
    assert!(p
        .resolve_recipient("DpcyqkendyzQd6yvDyHt9BEpUp2EnmXbEFUnpqAXpFAZ")
        .is_err());
    let rule = p.resolve_mint("USDC").unwrap();
    assert!(p.check_amount(rule, "500").is_ok());
    assert!(p.check_amount(rule, "500.000001").is_err());
}

#[test]
fn policy_parses_the_host_flat_string_config() {
    // The ZeroClaw host stores plugin config as HashMap<String, String>
    // (crates/zeroclaw-config PluginEntryConfig) and injects `__config` as a
    // flat JSON object of strings, so structured values arrive as JSON in a
    // string. This is the exact shape call_execute produces.
    let cfg = json!({
        "rpc_url": "https://api.mainnet-beta.solana.com",
        "mints": "[{\"mint\":\"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\
                    \"symbol\":\"USDC\",\"decimals\":6,\"per_proposal_cap\":\"500\"}]",
        "recipients": "{\"ana\":\"F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68\"}",
        "max_memo_len": "64"
    });
    let p = Policy::from_config(&cfg).unwrap();
    assert!(p.resolve_mint("usdc").is_ok());
    assert!(p.resolve_recipient("ana").is_ok());
    assert_eq!(p.max_memo_len, 64);

    // Malformed JSON inside the string is a loud refusal, not a missing key.
    let bad = json!({
        "mints": "[{\"mint\": nope]",
        "recipients": "{\"ana\":\"F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68\"}"
    });
    let err = Policy::from_config(&bad).unwrap_err();
    assert!(err.contains("not valid JSON"), "got: {err}");

    // A present but non-numeric max_memo_len refuses instead of silently
    // defaulting.
    let bad_len = json!({
        "mints": "[{\"mint\":\"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\
                    \"symbol\":\"USDC\",\"decimals\":6,\"per_proposal_cap\":\"500\"}]",
        "recipients": "{\"ana\":\"F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68\"}",
        "max_memo_len": "lots"
    });
    assert!(Policy::from_config(&bad_len).is_err());
}

fn mint_cfg(decimals: &str, token_2022: Value) -> Value {
    json!({
        "mints": [{
            "mint": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
            "symbol": "USDC",
            "decimals": decimals,
            "per_proposal_cap": "500",
            "token_2022": token_2022,
        }],
        "recipients": {"ana": "F65MT4J3kSRdyPMehKvuUvHmpCktrH9Q8n7J8dsHit68"}
    })
}

#[test]
fn policy_bounds_decimals_and_parses_token2022_string() {
    // Absurd decimals fail closed at config time.
    assert!(Policy::from_config(&mint_cfg("20", json!(false))).is_err());
    assert!(Policy::from_config(&mint_cfg("6", json!(false))).is_ok());

    // The host stores everything as strings: "true"/"false" must parse, and a
    // Token-2022 mint must NOT silently resolve to the legacy token program.
    let p = Policy::from_config(&mint_cfg("6", json!("true"))).unwrap();
    assert!(p.resolve_mint("USDC").unwrap().token_2022);
    let p = Policy::from_config(&mint_cfg("6", json!("false"))).unwrap();
    assert!(!p.resolve_mint("USDC").unwrap().token_2022);
    // A malformed boolean refuses rather than defaulting to false.
    assert!(Policy::from_config(&mint_cfg("6", json!("yes"))).is_err());
}

#[test]
fn sanitize_strips_bidi_zero_width_and_caps_bytes() {
    use quorum_core::policy::sanitize_untrusted;
    // Bidi override, zero-width space, and a line separator are all removed.
    let dirty = "USDC\u{202E}evil\u{200B}x\u{2028}y";
    let clean = sanitize_untrusted(dirty, 64);
    assert_eq!(clean, "USDCevilxy");
    assert!(!clean
        .chars()
        .any(|c| c == '\u{202E}' || c == '\u{200B}' || c == '\u{2028}'));
    // The cap is in bytes: a 4-byte emoji budget of 6 keeps at most one.
    let capped = sanitize_untrusted("\u{1F4B0}\u{1F4B0}\u{1F4B0}", 6);
    assert!(
        capped.len() <= 6,
        "byte length {} exceeds cap",
        capped.len()
    );
}

#[test]
fn policy_memo_is_byte_capped_and_stripped() {
    let cfg = mint_cfg("6", json!(false));
    let mut cfg = cfg;
    cfg["max_memo_len"] = json!(8);
    let p = Policy::from_config(&cfg).unwrap();
    // Control chars stripped; multi-byte content capped in bytes not chars.
    let memo = p.sanitize_memo(Some("ab\ncd\u{1F4B0}\u{1F4B0}\u{1F4B0}"));
    let memo = memo.unwrap();
    assert!(!memo.contains('\n'));
    assert!(
        memo.len() <= 8,
        "memo byte length {} exceeds cap",
        memo.len()
    );
}

#[test]
fn format_base_amount_never_traps_for_any_decimals() {
    // decimals >= 64 would make 10u64.pow wrap to 0 -> divide-by-zero trap in
    // the overflow-checks-off release build; the u128/checked path is safe.
    for d in [0u8, 6, 9, 18, 19, 20, 38, 39, 64, 200, 255] {
        let s = format_base_amount(1_234_567, d);
        assert!(!s.is_empty());
    }
    assert_eq!(format_base_amount(1_500_000, 6), "1.5");
}

#[test]
fn parse_ui_amount_fails_closed_on_oversized_decimals() {
    // 10^39 overflows u128; must be a Result error, not a panic.
    assert!(parse_ui_amount("1", 39).is_err());
    assert!(parse_ui_amount("1.5", 40).is_err());
}

#[test]
fn shortvec_rejects_noncanonical_and_over_u16() {
    // Canonical values still round-trip.
    for n in [0usize, 1, 127, 128, 16383, 65535] {
        let mut buf = Vec::new();
        shortvec_len(n, &mut buf);
        assert_eq!(shortvec_read(&buf).unwrap().0, n);
    }
    // Non-minimal encoding of 0 is rejected.
    assert!(shortvec_read(&[0x80, 0x00]).is_err());
    // A value above u16::MAX is rejected.
    assert!(shortvec_read(&[0xff, 0xff, 0x7f]).is_err());
}

#[test]
fn reader_take_is_overflow_safe_on_huge_length() {
    // A vault_transaction_create claiming a 0xFFFFFFFF message length must
    // return an error, never overflow the 32-bit wasm bounds check and trap.
    let mut data = Vec::new();
    data.extend_from_slice(&DISC_VAULT_TRANSACTION_CREATE);
    data.push(0); // vault_index
    data.push(0); // ephemeral_signers
    data.extend_from_slice(&0xFFFF_FFFFu32.to_le_bytes()); // message length
    assert!(decode_vault_transaction_create_args(&data).is_err());
}

#[test]
fn parser_rejects_versioned_v0_message() {
    // Base64 of [0x00, 0x80, 0x00, 0x00]: zero signatures, then a message
    // whose first byte has the version bit set. Must be rejected, not
    // misparsed as a huge signature/header.
    let err = parse_tx_base64("AIAAAA==").unwrap_err();
    assert!(err.contains("versioned"), "got: {err}");
}

#[test]
fn compile_rejects_too_many_signatures() {
    // 128+ signers would set the high bit of the first message byte and
    // collide with the v0 marker; the compiler must refuse.
    let payer = Pubkey([1u8; 32]);
    let accounts: Vec<AccountMeta> = (0u16..200)
        .map(|i| {
            let mut b = [0u8; 32];
            b[0..2].copy_from_slice(&i.to_le_bytes());
            b[31] = 9;
            AccountMeta::writable(Pubkey(b), true)
        })
        .collect();
    let ix = Instruction {
        program_id: Pubkey([7u8; 32]),
        accounts,
        data: vec![0],
    };
    assert!(compile_legacy_message(&payer, &[ix], &[0u8; 32]).is_err());
}
